/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  defaultSidebar: [
    {
      type: 'category',
      label: 'Hardware',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'hardware'}],
    },
    {
      type: 'category',
      label: 'SDK',
      link: {type: 'doc', id: 'sdk/index'},
      items: [
        'sdk/2.x/setup',
        {
          type: 'category',
          label: 'API',
          link: {type: 'generated-index', slug: '/sdk/2.x/api'},
          items: [{type: 'autogenerated', dirName: 'sdk/2.x/api'}],
        },
        {type: 'doc', id: 'sdk/1.x/setup', className: 'sdk-1x-hidden'},
        {
          type: 'category',
          label: 'API',
          link: {type: 'generated-index', slug: '/sdk/1.x/api'},
          className: 'sdk-1x-hidden',
          items: [
            {type: 'doc', id: 'sdk/1.x/api/mainboard', className: 'sdk-1x-hidden'},
            {type: 'doc', id: 'sdk/1.x/api/result', className: 'sdk-1x-hidden'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
  ],
};

module.exports = sidebars;
